apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        securityContext:
          allowPrivilegeEscalation: false
        image: controller:latest
        imagePullPolicy: Always
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-addr=127.0.0.1:8080"
        - "--leader-elect"
        - "--leader-election-id=anchore-engine"
        env:
        - name: RELATED_IMAGE_ANCHORE_ENGINE
          value: docker.io/anchore/anchore-engine:v0.10.0
        - name: RELATED_IMAGE_ANCHORE_ENTERPRISE
          value: docker.io/anchore/enterprise:v3.1.0
        - name: RELATED_IMAGE_ANCHORE_UI
          value: docker.io/anchore/enterprise-ui:v3.1.0
        - name: RELATED_IMAGE_ANCHORE_POSTGRESQL
          value: docker.io/postgres:9.6.18
        - name: RELATED_IMAGE_ANCHORE_FEEDS_DB
          value: docker.io/postgres:9.6.18
        - name: RELATED_IMAGE_ANCHORE_REDIS_REGISTRY
          value: docker.io
        - name: RELATED_IMAGE_ANCHORE_REDIS_REPOSITORY
          value: bitnami/redis
        - name: RELATED_IMAGE_ANCHORE_REDIS_TAG
          value: 6.0.8-debian-10-r0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 90Mi
          requests:
            cpu: 100m
            memory: 60Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
