apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: engine-operator-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-operator-manager
  namespace: system
  labels:
    control-plane: engine-operator-manager
spec:
  selector:
    matchLabels:
      control-plane: engine-operator-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: engine-operator-manager
    spec:
      containers:
      - image: "docker.io/anchore/engine-operator:v0.2.0"
        args:
        - "--enable-leader-election"
        - "--leader-election-id=engine-operator"
        name: engine-operator-manager
        livenessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 90Mi
          requests:
            cpu: 100m
            memory: 60Mi
      terminationGracePeriodSeconds: 10
