# permissions for end users to edit anchoreengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anchoreengine-editor-role
rules:
- apiGroups:
  - charts.anchore.io
  resources:
  - anchoreengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.anchore.io
  resources:
  - anchoreengines/status
  verbs:
  - get
